
USE speakeasy;

CREATE TABLE users (
user_id INT(6) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(32) NOT NULL UNIQUE,
password VARCHAR(32) NOT NULL,
distance SMALLINT(2) NOT NULL DEFAULT 25,
latitude FLOAT(33,30) NOT NULL,
longitude FLOAT(33,30) NOT NULL
);

CREATE TABLE messages (
message_id INT(6) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(32) NOT NULL,
room VARCHAR(32) NOT NULL,
message VARCHAR(256) NOT NULL,
time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
room_id INT(6) ZEROFILL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(32) NOT NULL UNIQUE,
expire DATETIME NOT NULL,
creator VARCHAR(32) NOT NULL,
latitude FLOAT(33,30) NOT NULL,
longitude FLOAT(33,30) NOT NULL
);

ALTER TABLE messages
ADD FOREIGN KEY(username)
REFERENCES users(username)
ON DELETE CASCADE;

ALTER TABLE messages
ADD FOREIGN KEY(room)
REFERENCES rooms(name)
ON DELETE CASCADE;

ALTER TABLE rooms
ADD FOREIGN KEY(creator)
REFERENCES users(username)
ON DELETE CASCADE;